spring.application.name=pesaflow
spring.datasource.url=jdbc:postgresql://localhost:5432/pesaflow
spring.datasource.username=postgres
spring.datasource.password=Cisko@2002

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
